# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 457978641ca645fa0666d6c84c3cd5ff485e17bafc3ad1562057e0232e01e86366d42dc5e9ff0c041740901048781d021a3a92f212fdadd9b4986931c633c546

test:
  secret_key_base: 7325f6bb7baa7d7cf4e2f17c2477d36c3650277d8ac12b5ab9017dc445bd101255f1fb20da62c5368baaeae9cea06c29dbf5416dff7546fb08a7171e2b928cfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
